 
INSERT INTO `nationalities` (`id`, `name_ar`, `name_en`, `deleted`, `created_at`, `updated_at`) VALUES
(1, 'سعودي', 'Saudi', '0', '2021-02-28 04:34:35', '2021-12-27 11:32:01'),
(2, 'اماراتي', 'amaraty', '0', '2021-03-23 12:12:27', '2021-12-27 11:32:15'),
(3, 'آلاندي', 'Aland Islander', '0', NULL, NULL),
(4, 'جزائري', 'Algerian', '0', NULL, NULL),
(5, 'أمريكي سامواني', 'American Samoan', '0', NULL, NULL),
(6, 'أندوري', 'Andorran', '0', NULL, NULL),
(7, 'أنقولي', 'Angolan', '0', NULL, NULL),
(8, 'أنغويلي', 'Anguillan', '0', NULL, NULL),
(9, 'أنتاركتيكي', 'Antarctican', '0', NULL, NULL),
(10, 'بربودي', 'Antiguan', '0', NULL, NULL),
(11, 'أرجنتيني', 'Argentinian', '0', NULL, NULL),
(12, 'أرميني', 'Armenian', '0', NULL, NULL),
(13, 'أوروبهيني', 'Aruban', '0', NULL, NULL),
(14, 'أسترالي', 'Australian', '0', NULL, NULL),
(15, 'نمساوي', 'Austrian', '0', NULL, NULL),
(16, 'أذربيجاني', 'Azerbaijani', '0', NULL, NULL),
(17, 'باهاميسي', 'Bahamian', '0', NULL, NULL),
(18, 'بحريني', 'Bahraini', '0', NULL, NULL),
(19, 'بنغلاديشي', 'Bangladeshi', '0', NULL, NULL),
(20, 'بربادوسي', 'Barbadian', '0', NULL, NULL),
(21, 'روسي', 'Belarusian', '0', NULL, NULL),
(22, 'بلجيكي', 'Belgian', '0', NULL, NULL),
(23, 'بيليزي', 'Belizean', '0', NULL, NULL),
(24, 'بنيني', 'Beninese', '0', NULL, NULL),
(25, 'سان بارتيلمي', 'Saint Barthelmian', '0', NULL, NULL),
(26, 'برمودي', 'Bermudan', '0', NULL, NULL),
(27, 'بوتاني', 'Bhutanese', '0', NULL, NULL),
(28, 'بوليفي', 'Bolivian', '0', NULL, NULL),
(29, 'بوسني/هرسكي', 'Bosnian / Herzegovinian', '0', NULL, NULL),
(30, 'بوتسواني', 'Botswanan', '0', NULL, NULL),
(31, 'بوفيهي', 'Bouvetian', '0', NULL, NULL),
(32, 'برازيلي', 'Brazilian', '0', NULL, NULL),
(33, 'إقليم المحيط الهندي البريطاني', 'British Indian Ocean Territory', '0', NULL, NULL),
(34, 'بروني', 'Bruneian', '0', NULL, NULL),
(35, 'بلغاري', 'Bulgarian', '0', NULL, NULL),
(36, 'بوركيني', 'Burkinabe', '0', NULL, NULL),
(37, 'بورونيدي', 'Burundian', '0', NULL, NULL),
(38, 'كمبودي', 'Cambodian', '0', NULL, NULL),
(39, 'كاميروني', 'Cameroonian', '0', NULL, NULL),
(40, 'كندي', 'Canadian', '0', NULL, NULL),
(41, 'الرأس الأخضر', 'Cape Verdean', '0', NULL, NULL),
(42, 'كايماني', 'Caymanian', '0', NULL, NULL),
(43, 'أفريقي', 'Central African', '0', NULL, NULL),
(44, 'تشادي', 'Chadian', '0', NULL, NULL),
(45, 'شيلي', 'Chilean', '0', NULL, NULL),
(46, 'صيني', 'Chinese', '0', NULL, NULL),
(47, 'جزيرة عيد الميلاد', 'Christmas Islander', '0', NULL, NULL),
(48, 'جزر كوكوس', 'Cocos Islander', '0', NULL, NULL),
(49, 'كولومبي', 'Colombian', '0', NULL, NULL),
(50, 'جزر القمر', 'Comorian', '0', NULL, NULL),
(51, 'كونغي', 'Congolese', '0', NULL, NULL),
(52, 'جزر كوك', 'Cook Islander', '0', NULL, NULL),
(53, 'كوستاريكي', 'Costa Rican', '0', NULL, NULL),
(54, 'كوراتي', 'Croatian', '0', NULL, NULL),
(55, 'كوبي', 'Cuban', '0', NULL, NULL),
(56, 'قبرصي', 'Cypriot', '0', NULL, NULL),
(57, 'كوراساوي', 'Curacian', '0', NULL, NULL),
(58, 'تشيكي', 'Czech', '0', NULL, NULL),
(59, 'دنماركي', 'Danish', '0', NULL, NULL),
(60, 'جيبوتي', 'Djiboutian', '0', NULL, NULL),
(61, 'دومينيكي', 'Dominican', '0', NULL, NULL),
(62, 'دومينيكي', 'Dominican', '0', NULL, NULL),
(63, 'إكوادوري', 'Ecuadorian', '0', NULL, NULL),
(64, 'مصري', 'Egyptian', '0', NULL, NULL),
(65, 'سلفادوري', 'Salvadoran', '0', NULL, NULL),
(66, 'غيني', 'Equatorial Guinean', '0', NULL, NULL),
(67, 'إريتيري', 'Eritrean', '0', NULL, NULL),
(68, 'استوني', 'Estonian', '0', NULL, NULL),
(69, 'أثيوبي', 'Ethiopian', '0', NULL, NULL),
(70, 'فوكلاندي', 'Falkland Islander', '0', NULL, NULL),
(71, 'جزر فارو', 'Faroese', '0', NULL, NULL),
(72, 'فيجي', 'Fijian', '0', NULL, NULL),
(73, 'فنلندي', 'Finnish', '0', NULL, NULL),
(74, 'فرنسي', 'French', '0', NULL, NULL),
(75, 'غويانا الفرنسية', 'French Guianese', '0', NULL, NULL),
(76, 'بولينيزيي', 'French Polynesian', '0', NULL, NULL),
(77, 'فرنسي جنوبي', 'French Southern', '0', NULL, NULL),
(78, 'غابوني', 'Gabonese', '0', NULL, NULL),
(79, 'غامبي', 'Gambian', '0', NULL, NULL),
(80, 'جيورجي', 'Georgian', '0', NULL, NULL),
(81, 'ألماني', 'German', '0', NULL, NULL),
(82, 'غاني', 'Ghanaian', '0', NULL, NULL),
(83, 'جبل طارق', 'Gibraltar', '0', NULL, NULL),
(84, 'غيرنزي', 'Guernsian', '0', NULL, NULL),
(85, 'يوناني', 'Greek', '0', NULL, NULL),
(86, 'جرينلاندي', 'Greenlandic', '0', NULL, NULL),
(87, 'غرينادي', 'Grenadian', '0', NULL, NULL),
(88, 'جزر جوادلوب', 'Guadeloupe', '0', NULL, NULL),
(89, 'جوامي', 'Guamanian', '0', NULL, NULL),
(90, 'غواتيمالي', 'Guatemalan', '0', NULL, NULL),
(91, 'غيني', 'Guinean', '0', NULL, NULL),
(92, 'غيني', 'Guinea-Bissauan', '0', NULL, NULL),
(93, 'غياني', 'Guyanese', '0', NULL, NULL),
(94, 'هايتي', 'Haitian', '0', NULL, NULL),
(95, 'جزيرة هيرد وجزر ماكدونالد', 'Heard and Mc Donald Islanders', '0', NULL, NULL),
(96, 'هندوراسي', 'Honduran', '0', NULL, NULL),
(97, 'هونغ كونغي', 'Hongkongese', '0', NULL, NULL),
(98, 'مجري', 'Hungarian', '0', NULL, NULL),
(99, 'آيسلندي', 'Icelandic', '0', NULL, NULL),
(100, 'هندي', 'Indian', '0', NULL, NULL),
(101, 'ماني', 'Manx', '0', NULL, NULL),
(102, 'أندونيسيي', 'Indonesian', '0', NULL, NULL),
(103, 'إيراني', 'Iranian', '0', NULL, NULL),
(104, 'عراقي', 'Iraqi', '0', NULL, NULL),
(105, 'إيرلندي', 'Irish', '0', NULL, NULL),
(106, 'إيطالي', 'Italian', '0', NULL, NULL),
(107, 'ساحل العاج', 'Ivory Coastian', '0', NULL, NULL),
(108, 'جيرزي', 'Jersian', '0', NULL, NULL),
(109, 'جمايكي', 'Jamaican', '0', NULL, NULL),
(110, 'ياباني', 'Japanese', '0', NULL, NULL),
(111, 'أردني', 'Jordanian', '0', NULL, NULL),
(112, 'كازاخستاني', 'Kazakh', '0', NULL, NULL),
(113, 'كيني', 'Kenyan', '0', NULL, NULL),
(114, 'كيريباتي', 'I-Kiribati', '0', NULL, NULL),
(115, 'كوري', 'North Korean', '0', NULL, NULL),
(116, 'كوري', 'South Korean', '0', NULL, NULL),
(117, 'كوسيفي', 'Kosovar', '0', NULL, NULL),
(118, 'كويتي', 'Kuwaiti', '0', NULL, NULL),
(119, 'قيرغيزستاني', 'Kyrgyzstani', '0', NULL, NULL),
(120, 'لاوسي', 'Laotian', '0', NULL, NULL),
(121, 'لاتيفي', 'Latvian', '0', NULL, NULL),
(122, 'لبناني', 'Lebanese', '0', NULL, NULL),
(123, 'ليوسيتي', 'Basotho', '0', NULL, NULL),
(124, 'ليبيري', 'Liberian', '0', NULL, NULL),
(125, 'ليبي', 'Libyan', '0', NULL, NULL),
(126, 'ليختنشتيني', 'Liechtenstein', '0', NULL, NULL),
(127, 'لتوانيي', 'Lithuanian', '0', NULL, NULL),
(128, 'لوكسمبورغي', 'Luxembourger', '0', NULL, NULL),
(129, 'سريلانكي', 'Sri Lankian', '0', NULL, NULL),
(130, 'ماكاوي', 'Macanese', '0', NULL, NULL),
(131, 'مقدوني', 'Macedonian', '0', NULL, NULL),
(132, 'مدغشقري', 'Malagasy', '0', NULL, NULL),
(133, 'مالاوي', 'Malawian', '0', NULL, NULL),
(134, 'ماليزي', 'Malaysian', '0', NULL, NULL),
(135, 'مالديفي', 'Maldivian', '0', NULL, NULL),
(136, 'مالي', 'Malian', '0', NULL, NULL),
(137, 'مالطي', 'Maltese', '0', NULL, NULL),
(138, 'مارشالي', 'Marshallese', '0', NULL, NULL),
(139, 'مارتينيكي', 'Martiniquais', '0', NULL, NULL),
(140, 'موريتانيي', 'Mauritanian', '0', NULL, NULL),
(141, 'موريشيوسي', 'Mauritian', '0', NULL, NULL),
(142, 'مايوتي', 'Mahoran', '0', NULL, NULL),
(143, 'مكسيكي', 'Mexican', '0', NULL, NULL),
(144, 'مايكرونيزيي', 'Micronesian', '0', NULL, NULL),
(145, 'مولديفي', 'Moldovan', '0', NULL, NULL),
(146, 'مونيكي', 'Monacan', '0', NULL, NULL),
(147, 'منغولي', 'Mongolian', '0', NULL, NULL),
(148, 'الجبل الأسود', 'Montenegrin', '0', NULL, NULL),
(149, 'مونتسيراتي', 'Montserratian', '0', NULL, NULL),
(150, 'مغربي', 'Moroccan', '0', NULL, NULL),
(151, 'موزمبيقي', 'Mozambican', '0', NULL, NULL),
(152, 'ميانماري', 'Myanmarian', '0', NULL, NULL),
(153, 'ناميبي', 'Namibian', '0', NULL, NULL),
(154, 'نوري', 'Nauruan', '0', NULL, NULL),
(155, 'نيبالي', 'Nepalese', '0', NULL, NULL),
(156, 'هولندي', 'Dutch', '0', NULL, NULL),
(157, 'هولندي', 'Dutch Antilier', '0', NULL, NULL),
(158, 'كاليدوني', 'New Caledonian', '0', NULL, NULL),
(159, 'نيوزيلندي', 'New Zealander', '0', NULL, NULL),
(160, 'نيكاراجوي', 'Nicaraguan', '0', NULL, NULL),
(161, 'نيجيري', 'Nigerien', '0', NULL, NULL),
(162, 'نيجيري', 'Nigerian', '0', NULL, NULL),
(163, 'ني', 'Niuean', '0', NULL, NULL),
(164, 'نورفوليكي', 'Norfolk Islander', '0', NULL, NULL),
(165, 'ماريني', 'Northern Marianan', '0', NULL, NULL),
(166, 'نرويجي', 'Norwegian', '0', NULL, NULL),
(167, 'عماني', 'Omani', '0', NULL, NULL),
(168, 'باكستاني', 'Pakistani', '0', NULL, NULL),
(169, 'بالاوي', 'Palauan', '0', NULL, NULL),
(170, 'فلسطيني', 'Palestinian', '0', NULL, NULL),
(171, 'بنمي', 'Panamanian', '0', NULL, NULL),
(172, 'بابوي', 'Papua New Guinean', '0', NULL, NULL),
(173, 'بارغاوي', 'Paraguayan', '0', NULL, NULL),
(174, 'بيري', 'Peruvian', '0', NULL, NULL),
(175, 'فلبيني', 'Filipino', '0', NULL, NULL),
(176, 'بيتكيرني', 'Pitcairn Islander', '0', NULL, NULL),
(177, 'بولندي', 'Polish', '0', NULL, NULL),
(178, 'برتغالي', 'Portuguese', '0', NULL, NULL),
(179, 'بورتي', 'Puerto Rican', '0', NULL, NULL),
(180, 'قطري', 'Qatari', '0', NULL, NULL),
(181, 'ريونيوني', 'Reunionese', '0', NULL, NULL),
(182, 'روماني', 'Romanian', '0', NULL, NULL),
(183, 'روسي', 'Russian', '0', NULL, NULL),
(184, 'رواندا', 'Rwandan', '0', NULL, NULL),
(185, 'سانت كيتس ونيفس', 'Kittitian/Nevisian', '0', NULL, NULL),
(186, 'ساينت مارتني فرنسي', 'St. Martian(French)', '0', NULL, NULL),
(187, 'ساينت مارتني هولندي', 'St. Martian(Dutch)', '0', NULL, NULL),
(188, 'سان بيير وميكلوني', 'St. Pierre and Miquelon', '0', NULL, NULL),
(189, 'سانت فنسنت وجزر غرينادين', 'Saint Vincent and the Grenadines', '0', NULL, NULL),
(190, 'ساموي', 'Samoan', '0', NULL, NULL),
(191, 'ماريني', 'Sammarinese', '0', NULL, NULL),
(192, 'ساو تومي وبرينسيبي', 'Sao Tomean', '0', NULL, NULL),
(193, 'أفغانستاني', 'Afghan', '0', NULL, NULL),
(194, 'سنغالي', 'Senegalese', '0', NULL, NULL),
(195, 'صربي', 'Serbian', '0', NULL, NULL),
(196, 'سيشيلي', 'Seychellois', '0', NULL, NULL),
(197, 'سيراليوني', 'Sierra Leonean', '0', NULL, NULL),
(198, 'سنغافوري', 'Singaporean', '0', NULL, NULL),
(199, 'سولفاكي', 'Slovak', '0', NULL, NULL),
(200, 'سولفيني', 'Slovenian', '0', NULL, NULL),
(201, 'جزر سليمان', 'Solomon Island', '0', NULL, NULL),
(202, 'صومالي', 'Somali', '0', NULL, NULL),
(203, 'أفريقي', 'South African', '0', NULL, NULL),
(204, 'لمنطقة القطبية الجنوبية', 'South Georgia and the South Sandwich', '0', NULL, NULL),
(205, 'سوادني جنوبي', 'South Sudanese', '0', NULL, NULL),
(206, 'إسباني', 'Spanish', '0', NULL, NULL),
(207, 'هيلاني', 'St. Helenian', '0', NULL, NULL),
(208, 'سوداني', 'Sudanese', '0', NULL, NULL),
(209, 'سورينامي', 'Surinamese', '0', NULL, NULL),
(210, 'سفالبارد ويان ماين', 'Svalbardian/Jan Mayenian', '0', NULL, NULL),
(211, 'سوازيلندي', 'Swazi', '0', NULL, NULL),
(212, 'سويدي', 'Swedish', '0', NULL, NULL),
(213, 'سويسري', 'Swiss', '0', NULL, NULL),
(214, 'سوري', 'Syrian', '0', NULL, NULL),
(215, 'تايواني', 'Taiwanese', '0', NULL, NULL),
(216, 'طاجيكستاني', 'Tajikistani', '0', NULL, NULL),
(217, 'تنزانيي', 'Tanzanian', '0', NULL, NULL),
(218, 'تايلندي', 'Thai', '0', NULL, NULL),
(219, 'تيموري', 'Timor-Lestian', '0', NULL, NULL),
(220, 'توغي', 'Togolese', '0', NULL, NULL),
(221, 'توكيلاوي', 'Tokelaian', '0', NULL, NULL),
(222, 'تونغي', 'Tongan', '0', NULL, NULL),
(223, 'ترينيداد وتوباغو', 'Trinidadian/Tobagonian', '0', NULL, NULL),
(224, 'تونسي', 'Tunisian', '0', NULL, NULL),
(225, 'تركي', 'Turkish', '0', NULL, NULL),
(226, 'تركمانستاني', 'Turkmen', '0', NULL, NULL),
(227, 'جزر توركس وكايكوس', 'Turks and Caicos Islands', '0', NULL, NULL),
(228, 'توفالي', 'Tuvaluan', '0', NULL, NULL),
(229, 'أوغندي', 'Ugandan', '0', NULL, NULL),
(230, 'أوكراني', 'Ukrainian', '0', NULL, NULL),
(231, 'ألباني', 'Albanian', '0', NULL, NULL),
(232, 'بريطاني', 'British', '0', NULL, NULL),
(233, 'أمريكي', 'American', '0', NULL, NULL),
(234, 'أمريكي', 'US Minor Outlying Islander', '0', NULL, NULL),
(235, 'أورغواي', 'Uruguayan', '0', NULL, NULL),
(236, 'أوزباكستاني', 'Uzbek', '0', NULL, NULL),
(237, 'فانواتي', 'Vanuatuan', '0', NULL, NULL),
(238, 'فنزويلي', 'Venezuelan', '0', NULL, NULL),
(239, 'فيتنامي', 'Vietnamese', '0', NULL, NULL),
(240, 'أمريكي', 'American Virgin Islander', '0', NULL, NULL),
(241, 'فاتيكاني', 'Vatican', '0', NULL, NULL),
(242, 'فوتوني', 'Wallisian/Futunan', '0', NULL, NULL),
(243, 'صحراوي', 'Sahrawian', '0', NULL, NULL),
(244, 'يمني', 'Yemeni', '0', NULL, NULL),
(245, 'زامبياني', 'Zambian', '0', NULL, NULL),
(246, 'زمبابوي', 'Zimbabwean', '0', NULL, NULL);

